language: c++
sudo: required
os: linux
dist: jammy
compiler:
  - clang

install:
  - ./scripts/update.sh
  - ./scripts/cmake.sh
  - ./scripts/vcpkg.sh exp
  - ./scripts/emsdk.sh exp
  - ./scripts/sonar-install.sh exp

script:
  - ./scripts/sonar.sh